import { Lead, LeadPriority, LeadSource, LeadStatus } from "./leads-types"

export const pipelineOrder: LeadStatus[] = ["new", "qualified", "proposal", "negotiation", "won", "lost"]

export const statusConfig: Record<LeadStatus, { label: string; className: string }> = {
  new: { label: "New", className: "bg-sky-500/10 text-sky-500 border-sky-500/20" },
  qualified: { label: "Qualified", className: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20" },
  proposal: { label: "Proposal", className: "bg-purple-500/10 text-purple-500 border-purple-500/20" },
  negotiation: { label: "Negotiation", className: "bg-amber-500/10 text-amber-500 border-amber-500/20" },
  won: { label: "Won", className: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20" },
  lost: { label: "Lost", className: "bg-zinc-500/10 text-zinc-500 border-zinc-500/20" },
}

export const priorityConfig: Record<LeadPriority, { label: string; className: string }> = {
  hot: { label: "Hot", className: "bg-red-500/10 text-red-500 border-red-500/20" },
  warm: { label: "Warm", className: "bg-orange-500/10 text-orange-500 border-orange-500/20" },
  cold: { label: "Cold", className: "bg-blue-500/10 text-blue-500 border-blue-500/20" },
}

export const adPlatformSources: LeadSource[] = ["facebook", "instagram", "tiktok"]

export const allSources: LeadSource[] = [
  "manual",
  "facebook",
  "instagram",
  "tiktok",
  "whatsapp",
  "website",
  "Website",
  "Referral",
  "Social Media",
  "Email",
  "Cold Call",
  "Facebook Ad",
  "Google Ad",
  "Instagram Ad",
  "LinkedIn",
]

export type SourceConfigEntry = { label: string; className: string; dotColor: string; platform?: string }

export const sourceConfig: Partial<Record<LeadSource, SourceConfigEntry>> & Record<string, SourceConfigEntry> = {
  manual:         { label: "Manual",      className: "bg-secondary/40 text-muted-foreground border-border/50",       dotColor: "bg-muted-foreground" },
  facebook:       { label: "Facebook",    className: "bg-blue-500/10 text-blue-400 border-blue-500/20",              dotColor: "bg-blue-400",   platform: "facebook" },
  instagram:      { label: "Instagram",   className: "bg-pink-500/10 text-pink-400 border-pink-500/20",              dotColor: "bg-pink-400",   platform: "instagram" },
  whatsapp:       { label: "WhatsApp",    className: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",     dotColor: "bg-emerald-400",platform: "whatsapp" },
  website:        { label: "Website",     className: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",        dotColor: "bg-indigo-400", platform: "website" },
  tiktok:         { label: "TikTok",      className: "bg-zinc-500/10 text-zinc-400 border-zinc-500/20",              dotColor: "bg-zinc-400",   platform: "tiktok" },
  Website:        { label: "Website",     className: "bg-blue-500/10 text-blue-400 border-blue-500/20",              dotColor: "bg-blue-400" },
  Referral:       { label: "Referral",    className: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",     dotColor: "bg-emerald-400" },
  "Social Media": { label: "Social",      className: "bg-purple-500/10 text-purple-400 border-purple-500/20",        dotColor: "bg-purple-400" },
  Email:          { label: "Email",       className: "bg-amber-500/10 text-amber-400 border-amber-500/20",           dotColor: "bg-amber-400" },
  "Cold Call":    { label: "Cold Call",   className: "bg-orange-500/10 text-orange-400 border-orange-500/20",        dotColor: "bg-orange-400" },
  "Facebook Ad":  { label: "FB Ad",       className: "bg-sky-500/10 text-sky-400 border-sky-500/20",                 dotColor: "bg-sky-400",    platform: "facebook" },
  "Google Ad":    { label: "Google Ad",   className: "bg-red-500/10 text-red-400 border-red-500/20",                 dotColor: "bg-red-400" },
  "Instagram Ad": { label: "IG Ad",       className: "bg-pink-500/10 text-pink-400 border-pink-500/20",              dotColor: "bg-pink-400",   platform: "instagram" },
  LinkedIn:       { label: "LinkedIn",    className: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",        dotColor: "bg-indigo-400" },
}

export const agents = ["James Donovan", "Sarah Mitchell", "Michael Chen", "Emily Rodriguez"]

export const propertyOptions = [
  "Manhattan Penthouse",
  "Beverly Hills Estate",
  "Miami Beach Condo",
  "Malibu Beach House",
  "San Francisco Loft",
  "Dubai Marina Villa",
]

export const availableTags = [
  "VIP",
  "Investor",
  "First-time Buyer",
  "Cash Buyer",
  "Relocating",
  "International",
  "Urgent",
]

export const initialLeads: Lead[] = [
  {
    id: 1,
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "+1 (555) 123-4567",
    whatsappNumber: "+15551234567",
    interestedProperties: ["Manhattan Penthouse"],
    property: "Manhattan Penthouse",
    budget: "$5.2M",
    status: "negotiation",
    priority: "hot",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "2 hours ago",
    avatar: "SM",
    score: 88,
    urgencyScore: 85,
    campaign: "Luxury NYC Q2",
    adSource: "Partner Referral",
    aiSummary: "High-value negotiation lead in final stages of the Manhattan Penthouse deal. Cash buyer with an urgent timeline — HOA legal review is the last remaining blocker. Recommend scheduling a closing call this week.",
    suggestedActions: ["Schedule closing call", "Share HOA legal summary", "Confirm wire transfer details"],
    tags: ["VIP", "Cash Buyer"],
    reminder: { date: "May 30, 2026", note: "Call to discuss HOA terms and finalize offer" },
    attachments: [
      { name: "Financial_Statement.pdf", size: "2.4 MB", type: "pdf" },
      { name: "ID_Verification.pdf", size: "1.1 MB", type: "pdf" },
    ],
    notes: ["Requested private evening showing", "Needs legal review for HOA terms"],
    timeline: [
      { id: "1-a", title: "WhatsApp follow-up sent", time: "2h ago" },
      { id: "1-b", title: "Offer document shared", time: "Yesterday" },
      { id: "1-c", title: "Lead qualified by agent", time: "2 days ago" },
    ],
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "+1 (555) 234-5678",
    whatsappNumber: "+15552345678",
    interestedProperties: ["Beverly Hills Estate", "Malibu Beach House"],
    property: "Beverly Hills Estate",
    budget: "$8.7M",
    status: "proposal",
    priority: "warm",
    source: "Website",
    assignedTo: "Sarah Mitchell",
    lastContact: "1 day ago",
    avatar: "MC",
    score: 72,
    urgencyScore: 62,
    campaign: "LA Luxury Homes",
    aiSummary: "High-budget investor comparing Beverly Hills Estate with a Malibu alternative. Proposal submitted — awaiting response. Strong financial profile with international background.",
    suggestedActions: ["Follow up on proposal", "Share Malibu comparison doc", "Schedule video call"],
    tags: ["Investor", "International"],
    attachments: [{ name: "Proof_of_Funds.pdf", size: "3.2 MB", type: "pdf" }],
    notes: ["Comparing with two Malibu properties"],
    timeline: [
      { id: "2-a", title: "Pricing proposal submitted", time: "1d ago" },
      { id: "2-b", title: "Discovery call completed", time: "3 days ago" },
    ],
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 345-6789",
    whatsappNumber: "+15553456789",
    interestedProperties: ["Miami Beach Condo"],
    property: "Miami Beach Condo",
    budget: "$3.1M",
    status: "qualified",
    priority: "hot",
    source: "Instagram Ad",
    assignedTo: "Michael Chen",
    lastContact: "5 hours ago",
    avatar: "ER",
    score: 81,
    urgencyScore: 78,
    campaign: "Miami Summer 2026",
    adSource: "IG Story — Beachfront Living",
    aiSummary: "First-time luxury buyer with a strong urgency signal. Looking for a fast close on Miami Beach Condo. Came in via Instagram ad campaign with high engagement. Prioritize scheduling a property viewing.",
    suggestedActions: ["Schedule property viewing", "Send financing options", "Send fast-close checklist"],
    tags: ["First-time Buyer", "Urgent"],
    reminder: { date: "May 29, 2026", note: "Schedule property viewing" },
    attachments: [],
    notes: ["Interested in fast closing window"],
    timeline: [
      { id: "3-a", title: "Qualification form completed", time: "5h ago" },
      { id: "3-b", title: "Lead created from Instagram ad", time: "1 day ago" },
    ],
  },
  {
    id: 4,
    name: "David Park",
    email: "david.park@email.com",
    phone: "+1 (555) 456-7890",
    whatsappNumber: "+15554567890",
    interestedProperties: ["San Francisco Loft", "Manhattan Penthouse"],
    property: "San Francisco Loft",
    budget: "$2.8M",
    status: "new",
    priority: "cold",
    source: "Email",
    assignedTo: "Emily Rodriguez",
    lastContact: "3 days ago",
    avatar: "DP",
    score: 45,
    urgencyScore: 30,
    tags: ["Relocating"],
    attachments: [],
    notes: ["Relocating from Seoul in Q3", "Needs pet-friendly building"],
    timeline: [{ id: "4-a", title: "Email inquiry received", time: "3d ago" }],
  },
  {
    id: 5,
    name: "Amanda Foster",
    email: "amanda.f@email.com",
    phone: "+1 (555) 567-8901",
    whatsappNumber: "+15555678901",
    interestedProperties: ["Malibu Beach House"],
    property: "Malibu Beach House",
    budget: "$16M",
    status: "won",
    priority: "hot",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "1 week ago",
    avatar: "AF",
    score: 95,
    urgencyScore: 20,
    campaign: "Malibu Elite",
    tags: ["VIP", "Cash Buyer", "Investor"],
    attachments: [
      { name: "Purchase_Agreement.pdf", size: "5.1 MB", type: "pdf" },
      { name: "Signed_Contract.pdf", size: "4.7 MB", type: "pdf" },
      { name: "Property_Inspection.pdf", size: "8.2 MB", type: "pdf" },
    ],
    notes: ["Deal closed successfully", "Prefers wire transfer"],
    timeline: [
      { id: "5-a", title: "Contract signed", time: "1wk ago" },
      { id: "5-b", title: "Final walkthrough done", time: "10d ago" },
      { id: "5-c", title: "Offer accepted", time: "2wk ago" },
    ],
  },
  {
    id: 6,
    name: "Robert Chang",
    email: "r.chang@email.com",
    phone: "+1 (555) 678-9012",
    whatsappNumber: "+15556789012",
    interestedProperties: ["Dubai Marina Villa"],
    property: "Dubai Marina Villa",
    budget: "$4.5M",
    status: "new",
    priority: "warm",
    source: "Cold Call",
    assignedTo: "Sarah Mitchell",
    lastContact: "Yesterday",
    avatar: "RC",
    score: 58,
    urgencyScore: 45,
    tags: ["International"],
    attachments: [],
    notes: ["Looking to buy before end of year"],
    timeline: [{ id: "6-a", title: "Cold call — expressed interest", time: "Yesterday" }],
  },
  {
    id: 7,
    name: "Lisa Thornton",
    email: "l.thornton@email.com",
    phone: "+1 (555) 789-0123",
    whatsappNumber: "+15557890123",
    interestedProperties: ["Beverly Hills Estate"],
    property: "Beverly Hills Estate",
    budget: "$9.1M",
    status: "qualified",
    priority: "warm",
    source: "Referral",
    assignedTo: "James Donovan",
    lastContact: "2 days ago",
    avatar: "LT",
    score: 67,
    urgencyScore: 55,
    tags: ["Investor"],
    duplicateOf: 2,
    attachments: [{ name: "Investor_Profile.pdf", size: "1.8 MB", type: "pdf" }],
    notes: ["Possible duplicate — similar budget and property interest as Michael Chen"],
    timeline: [
      { id: "7-a", title: "Referral from existing client", time: "2d ago" },
      { id: "7-b", title: "Initial call completed", time: "2d ago" },
    ],
  },
  {
    id: 8,
    name: "James Whitfield",
    email: "j.whitfield@email.com",
    phone: "+1 (555) 890-1234",
    whatsappNumber: "+15558901234",
    interestedProperties: ["Manhattan Penthouse"],
    property: "Manhattan Penthouse",
    budget: "$6.8M",
    status: "new",
    priority: "hot",
    source: "Google Ad",
    assignedTo: "James Donovan",
    lastContact: "4 hours ago",
    avatar: "JW",
    score: 74,
    urgencyScore: 80,
    campaign: "NYC Penthouse Q2",
    adSource: "Google Search — luxury penthouse nyc",
    tags: ["Cash Buyer"],
    attachments: [],
    notes: ["Submitted inquiry from Google ad at 11pm — high intent signal"],
    timeline: [
      { id: "8-a", title: "Lead created from Google Ad", time: "4h ago" },
    ],
  },
  {
    id: 9,
    name: "Priya Nair",
    email: "priya.n@email.com",
    phone: "+1 (555) 901-2345",
    whatsappNumber: "+15559012345",
    interestedProperties: ["San Francisco Loft"],
    property: "San Francisco Loft",
    budget: "$3.4M",
    status: "qualified",
    priority: "warm",
    source: "LinkedIn",
    assignedTo: "Emily Rodriguez",
    lastContact: "1 day ago",
    avatar: "PN",
    score: 63,
    urgencyScore: 50,
    campaign: "SF Tech Buyer Outreach",
    tags: ["Relocating", "Investor"],
    attachments: [],
    notes: ["Tech executive relocating from Bangalore", "Interested in rooftop access"],
    timeline: [
      { id: "9-a", title: "LinkedIn message responded", time: "1d ago" },
      { id: "9-b", title: "LinkedIn campaign reached", time: "3d ago" },
    ],
  },
  {
    id: 10,
    name: "Carlos Vega",
    email: "c.vega@email.com",
    phone: "+1 (555) 012-3456",
    whatsappNumber: "+15550123456",
    interestedProperties: ["Miami Beach Condo"],
    property: "Miami Beach Condo",
    budget: "$2.5M",
    status: "lost",
    priority: "cold",
    source: "Facebook Ad",
    assignedTo: "Michael Chen",
    lastContact: "2 weeks ago",
    avatar: "CV",
    score: 28,
    urgencyScore: 10,
    campaign: "Miami Beach Summer",
    adSource: "FB Carousel — Miami Condos",
    tags: [],
    attachments: [],
    notes: ["Went with a competing listing in Brickell"],
    timeline: [
      { id: "10-a", title: "Lead marked lost — competitor chosen", time: "2wk ago" },
      { id: "10-b", title: "Property viewing scheduled", time: "3wk ago" },
    ],
  },
]
